### ISSUE TITLE
How to use Cookies for multiple users in PHP?

### ISSUE THREAD

**Issue by modInfo** [pierredavidbelanger/chatter-bot-api#13]
it is possible for cookies for separate user in Cleverbot?
eg: user1_cookie.txt, user2_cookie.txt, user3_cookie.txt

**Comment by pierredavidbelanger** [comment]
I hope I understand you question.

This library already supports being used by many concurrent users.

After creating a bot:
```
$factory = new ChatterBotFactory();
$bot = $factory->create(ChatterBotType::CLEVERBOT);
```

You just have to create a session per user (and serialize it into the session to be reused in each request of this user):
```
$botsession = $bot->createSession();
```

Here is something I wrote about this some time ago:
https://code.google.com/p/chatter-bot-api/issues/detail?id=3#c5

**Comment by modInfo** [comment]
I was concerned about something similar
```
function cleverbot($s,$userid) {
    require 'cleverbot.php';
    $factory = new ChatterBotFactory();

    $bot1 = $factory->create(ChatterBotType::CLEVERBOT);
    if ( file_exists('user' . $userid. '-cookie.txt') ) {
         $bot1session = $bot1->LoadSession('user' . $userid. '-cookie.txt');
    } else {
         $bot1session = $bot1->createSession('user' . $userid. '-cookie.txt');
    }
    $s = $bot1session->think($s);
    return $s;
}
```

**Comment by pierredavidbelanger** [comment]
The logic is almost fine, just do something like this:

<pre>
function cleverbot($s,$userid) {
    require 'cleverbot.php';
    $factory = new ChatterBotFactory();

    $bot1 = $factory->create(ChatterBotType::CLEVERBOT);
    if ( file_exists('user' . $userid. '-cookie.txt') ) {
         $bot1session = <b><i>...unserialize content of file 'user' . $userid. '-cookie.txt'</i></b>
    } else {
         $bot1session = $bot1->createSession(<b><strike>'user' . $userid. '-cookie.txt'</strike></b>);
    }
    $s = $bot1session->think($s);
    <b><i>...serialize $bot1session into file 'user' . $userid. '-cookie.txt'</i></b>
    return $s;
}
</pre>

**Comment by modInfo** [comment]
Thanks, it works. :)
