### ISSUE TITLE
utf8 encodnig fault in polish in cleverbot

### ISSUE THREAD

**Issue by modInfo** [pierredavidbelanger/chatter-bot-api#14]
bot1> "Te|017C nie wiesz?" should: "Też nie wiesz?"
bot2> "Ty lepiej jed|017A na PGA." should: "Ty lepiej jedź na PGA."
bot2> "W jakim mie|015Bcie?" should: "W jakim mieście?"

How to fix encodnig?

**Comment by pierredavidbelanger** [comment]
Is the [cleverbot](http://www.cleverbot.com/) web site is showing the same problem ?
If its the case, I guess I can not help :)

**Comment by modInfo** [comment]
On the website it works correctly.

**Comment by pierredavidbelanger** [comment]
Nice catch.

Indeed, Cleverbot seems to send some unicode chars in this pattern |xxxx where xxxx is the hex value of the unicode.

[This commit](https://github.com/pierredavidbelanger/chatter-bot-api/commit/52582f46a5be7af531b25ddbe567b70fce3d8649) will handle that.

Give it a try, and let me know if it works for you.

Thank you!

**Comment by modInfo** [comment]
It works, thanks for a quick response
