### ISSUE TITLE
Problem with Jabberwacky

### ISSUE THREAD

**Issue by Carleslc** [pierredavidbelanger/chatter-bot-api#19]
Hello,
With this code:

``` java
ChatterBotFactory factory = new ChatterBotFactory();
try {
    ChatterBot bot = factory.create(ChatterBotType.JABBERWACKY, null);
    ChatterBotSession botSession = bot.createSession();
    String ans = botSession.think("something");
} catch (Exception e) {}
```

String ans always is:

``` java
"if(ob== null||cc==0) return true;if(cc==13||cc==3){uniEsc1();ob.form.submit()};return true;}"
```

Debugging the code the problem is on Cleverbot.class:97, that is:

``` java
responseThought.setText(Utils.stringAtIndex(responseValues, 16));
```

It can be solved changing the text set to:

``` java
UtilsBotURL.stringAtIndex(responseValues, 50).replaceAll("\\<[^<>]*\\>", "")
```

However, this is an ugly solution.
I hope your answers.

Greetings!

**Comment by pierredavidbelanger** [comment]
Hi.
My Jabberwacky integration is not working properly since a couple months now.
I will have a look at your workaround.
Thank you !

**Comment by Derpolino** [comment]
And for Python ? :X

**Comment by pierredavidbelanger** [comment]
I will close this issue, I will not support Jabberwacky any more.
From what I was told (by the Cleverbot guys) Jabberwacky is just an old, slow and buggy precursor of Cleverbot.
