### ISSUE TITLE
Is it possible to force the language Cleverbot respond?

### ISSUE THREAD

**Issue by dreszczyk** [pierredavidbelanger/chatter-bot-api#23]
I tried adding header 
`Accept-Language:`
to fopen, but it doesnt work.

**Comment by pierredavidbelanger** [comment]
I did not even know that Cleverbot has multi language support.
I will need to investigate this one.

**Comment by dreszczyk** [comment]
Cleverbot speaks many languages. When I write in polish on the website he always responds in polish, but through the api it does polish/english, sometimes german.

Im counting on you, thanks for great api :)

**Comment by pierredavidbelanger** [comment]
I've played a little with the Java version, and made it works.

The latest java 1.4.0-SNAPSHOT version (this is a snapshot release only) now accepts an array of Locale that controls the languages the bot should respond into.

If I get good feedbacks with this, I will migrate the .NET, PHP and Python versions too.

**Comment by dreszczyk** [comment]
Is there any chance to move this to PHP?

**Comment by pierredavidbelanger** [comment]
Yeah, I will take some time for this.
I do not know exactly how I will do it though.
Maybe make [ChatterBot.createSession](https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/php/chatterbotapi.php#L58) take an optional array of [Locale](http://php.net/manual/en/class.locale.php) ?

**Comment by pierredavidbelanger** [comment]
Ok, here it is, [this commit](https://github.com/pierredavidbelanger/chatter-bot-api/commit/8d73130f6933fee30bd37efd42ac594e1ee11293) allows one to pass a string to `createSession` to change de default language.

So now you can do something like this:
```
    $factory = new ChatterBotFactory();
    $bot1 = $factory->create(ChatterBotType::CLEVERBOT);
    $bot1session = $bot1->createSession('fr-CA'); // for canadian french
```

This new param, is straight added as an [Accept-Language header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)

So, have a look at the [Language Tags spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.10) for the valid values you can use.

It feels like a hack, please test it and/or submit a PR to help me make this less smelly ;)
