### ISSUE TITLE
Getting 404 error from API

### ISSUE THREAD

**Issue by NeighbourJim** [pierredavidbelanger/chatter-bot-api#28]
Seems like Cleverbot screwed with the API again and broke it. All requests returning 404. Just letting you know.

**Comment by xNanochip** [comment]
Yep, happening for me as well. Anyone know of a fix?

**Comment by dreszczyk** [comment]
+1

**Comment by Gleydar** [comment]
Can anyone try replacing the url ending on `/webservicemin` to `/webservicemin?uc=165&`

**Comment by xNanochip** [comment]
Still 404 when replacing the link with that.

**Comment by NeighbourJim** [comment]
Changing the url to what @Gleydar suggested seemed to fix it for me.

**Comment by Gleydar** [comment]
Good, I will try to submit a push then
Am 18.05.2016 10:19 vorm. schrieb "NeighbourJim" <notifications@github.com>:

**Comment by pierredavidbelanger** [comment]
@Gleydar indeed, this seems to fix the problem, though I have no idea why :)

I will push a fix in a couple of minute.

**Comment by pierredavidbelanger** [comment]
Should be fixed now in all ports.

Also, for maven users, the new 1.4.2 release version will be available on maven central as soon as its cache clear.
