### ISSUE TITLE
Cleverbot down

### ISSUE THREAD

**Issue by azcc** [pierredavidbelanger/chatter-bot-api#29]
Today I downloaded the latest PHP version and Cleverbot does not work again. Is anyone having the same problem?
Thanks

**Comment by GelLiNN** [comment]
I just added this project as a dependency to an android project and the request to create session isn't working.  Any ideas?

**Comment by pierredavidbelanger** [comment]
@azcc It seems to work right now. It was probably only a small downtime at Cleverbot.

@GelLiNN I do not understand exactly what is not working. Give me more informations, like: what you have tried, what you expect, a stack trace if you have one.
