### ISSUE TITLE
Default constructor cannot handle exception type Exception thrown by implicit super constructor. Must define an explicit constructor

### ISSUE THREAD

**Issue by JPaulMora** [pierredavidbelanger/chatter-bot-api#32]
I believe Chatterbot class should throw exception

code with error:

````
ChatterBotFactory factory = new ChatterBotFactory();
ChatterBot cleverbot = factory.create(ChatterBotType.CLEVERBOT); 
````

the second line.

**Comment by pierredavidbelanger** [comment]
I am not sure I understand what you mean here.

I will suppose you are using Java.

[factory.create()](https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/main/java/com/google/code/chatterbotapi/ChatterBotFactory.java#L22) is declared to throw `Exception`.

You probably need to `try`/`catch` it.

**Comment by JPaulMora** [comment]
Wow, sorry for really bad Issue formatting, Im using Java and I get the error described in the title (exactly the title). looking it up online, tells me that if a `superclass() throws exception`, classes derived from it should too. Those two lines posted above are enough to trigger the error in Eclipse Mars. Thanks in advance.

**Comment by pierredavidbelanger** [comment]
"Those two lines posted above" are certainly not enough to trigger an error, let alone to compile :)
I mean, maybe you can post more code.

I am pretty sure this come from your code.

And, I guess you have something like this:

```
public class Parent {
    public Parent() throws Exception {
        ChatterBotFactory factory = new ChatterBotFactory();
        ChatterBot cleverbot = factory.create(ChatterBotType.CLEVERBOT); 
    }
}

public class Child extends Parent {
}
```


In that case, indeed, IDEs will underline the `Child` class and say that `Exception` is unhandled.

You can fix this by removing the `throws Exception` from the `Parent` ctor, and wrapping the `factory.create` into a `try` / `catch` block, as suggested in my first comment.

Or, more simply, adding an empty `Child` ctor that also `throws Exception` (this is what IntelliJ is suggesting me when I `Alt`-`Enter` on the error).

**Comment by JPaulMora** [comment]
I ended up not using the factory and calling the chatterbot constructor directly, that worked flawlessly.

I may try what you just posted though, thanks.
