### ISSUE TITLE
Cannot connect to the webserver of cleverbot

### ISSUE THREAD

**Issue by crazyhorse961** [pierredavidbelanger/chatter-bot-api#37]
Hello,
today the bot cannot connect to the web api;
http://pastebin.com/kgerBVhV that's the error.
This used to work yesterday...
If i tries to connect to that link it gives a 404 not found.
Any fix? I don't think code is needed

**Comment by RezzedUp** [comment]
I had the same problem, but updating to 1.4.5 fixed it for me.

**Comment by crazyhorse961** [comment]
I'm also using 1.4.5 (i'm pretty sure).
Tho i changed (just for the moment) to pandora bots

**Comment by slandau3** [comment]
After deleting my local copy of the java bots and re-downloading them, they still don't appear to be working correctly.

**Comment by crazyhorse961** [comment]
Also connecting to the api
http://www.cleverbot.com/webservicemin?uc=321&botapi=chatterbotapi
Gives a 404... we will wait an update then

**Comment by crazyhorse961** [comment]
EDIT: Also tried to update in case. Same error

**Comment by Sceat** [comment]
Same issue :speak_no_evil:

**Comment by crazyhorse961** [comment]
For the moment i suggest you using pandorabots, it works.

**Comment by pierredavidbelanger** [comment]
I do not know what happened.
It seems to work now.

**Comment by crazyhorse961** [comment]
Hello,
i wish to say that the problem is still occuring, for me.

**Comment by pierredavidbelanger** [comment]
@crazyhorse961 You will have to give me more information, because It is working fine for me just now, with the Java version 1.4.5.

**Comment by crazyhorse961** [comment]
Hello,
see my edit. Was my own error as the stacktrace was totally different and it got fixed.
Sorry for desturbing you guys
