### ISSUE TITLE
webservice error?

### ISSUE THREAD

**Issue by hvazquezod** [pierredavidbelanger/chatter-bot-api#39]
Hi guys. Using Java, receive 401 response from Cleverbot.
http://pastebin.com/XQjQPued

Any thoughts?

**Comment by DanielBlood** [comment]
It's been changed, I hope the Devs can figure out a fix.

**Comment by Skerberus** [comment]
http://www.cleverbot.com/webservicemin?uc=777&botapi=chatterbotapi
(neue Url)

**Comment by pierredavidbelanger** [comment]
Indeed, they (Cleverbot) contacted me yesterday:

> [...] To let you know, tomorrow we will be changing the uc parameter again on the unofficial Cleverbot API. We’ve now developed a method for changing that and a couple other parameters as often as needed without disrupting legitimate clients much. [...]

So you should expect this kind of problem happening more often from now on.

Because they want people to use their official API: https://www.cleverbot.com/api/

I will soon refactor this project to consume the official API too.

**Comment by hvazquezod** [comment]
Hi everyone, thanks for your comments. Just tested new url provided by @Skerberus, am receiving responses, but they don't seem to be related to previous inputs. There also seems to be some sort of a delay between requests (receiving empty messages). 

Might be doing something wrong on my end though! Will wait for update by @pierredavidbelanger [:

**Comment by crazyhorse961** [comment]
I can also confirm that there's a sort of delay between requests, around 9/10 times i get an empty message.

**Comment by Headline22** [comment]
If you're using Java and want to use their official API, I made a simple wrapper for it [here](https://github.com/Headline22/CleverBotAPI-Java). Otherwise, I know that the Exitor servers were having issues yesterday where requests prompted no response. Might want to try again today.

**Comment by DeJayDevelopment** [comment]
Same issue. Moving to @Headline22's wrapper for the time being.

**Comment by pierredavidbelanger** [comment]
Please see [v2 branch](https://github.com/pierredavidbelanger/chatter-bot-api/tree/v2#java) for a working Java version of this this project that uses the new [Cleverbot official API](https://www.cleverbot.com/api/). No code breaking changes were required, except that you will now need an API Key when calling `factory.create(ChatterBotType.CLEVERBOT, "YOURAPIKEY")`.
