### ISSUE TITLE
Hang on startup

### ISSUE THREAD

**Issue by egold555** [pierredavidbelanger/chatter-bot-api#43]
Hi. I have been using your code for quite awhile and now when I updated to v2 everything just hangs on startup. Code is below.. I am unsure why this happens.

static ChatterBotSession botSession;

ChatterBotFactory factory = new ChatterBotFactory();
ChatterBot bot = factory.create(ChatterBotType.CLEVERBOT, (API KEY HERE));
botSession = bot.createSession();

**Comment by egold555** [comment]
Bug on my part.

**Comment by pierredavidbelanger** [comment]
This v2 is fairly new, do not hesitate to send feedback.
Thank you!

**Comment by egold555** [comment]
There does seem to be one issue is with cleverbot, is that the message like 3/4ths of the time return an empty string. Not sure why though.

**Comment by pierredavidbelanger** [comment]
You are not the first to report this behaviour. I will investigate.
