### ISSUE TITLE
Any update on this?

### ISSUE THREAD

**Issue by ProjectPact** [pierredavidbelanger/chatter-bot-api#47]
Any plans on fixing the keys or finding a way around them? The java source isn't wanting to work for me (even version 2.0)

**Comment by pierredavidbelanger** [comment]
> Any plans on fixing the keys or finding a way around them? 

What do you mean by `fixing the keys` ?

> The java source isn't wanting to work for me (even version 2.0)

It is working for me and, as far as I know, for others also. If you can reproduce the problem, please post the detail here with a stack trace that shows the error.

**Comment by ProjectPact** [comment]
java.io.IOException: Server returned HTTP response code: 401 for URL: http://www.cleverbot.com/webservicemin?uc=777&botapi=chatterbotapi

**Comment by robomaeyhem** [comment]
Are you running version 2.0? If so, and it's still not working, paste the stack trace

**Comment by pierredavidbelanger** [comment]
@ProjectPact this URL is not the official one (no not version 2).
Please have a look at this:
https://github.com/pierredavidbelanger/chatter-bot-api/tree/v2#maven
