### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by psycholyzern** [pierredavidbelanger/chatter-bot-api#7]
Got that error on cleverbot. Pandora is working great.

**Comment by pierredavidbelanger** [comment]
I just run the little [test application](https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/java/src/test/java/com/google/code/chatterbotapi/test/ChatterBotApiTest.java), and it runs ok.

Sometime, Cleverbot is just not available.

Are you able to reproduce the problem ?

**Comment by psycholyzern** [comment]
Somehow it returned me 403 forbidden error. But it is working great now!
Btw, thanks for replied to my issue :D
